/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Punto;
import Modelo.Trio;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.util.ArrayList;

/**
 *
 * @author SaulRC1
 */
public class PanelPuntos extends javax.swing.JPanel {
    
    private ArrayList<Punto> Puntos = null;
    private Trio trio_mas_cercano = null;
 
    
    /**
     * Creates new form PanelPuntos
     */
    public PanelPuntos() {
        setPreferredSize(new Dimension(6000, 6000));
        initComponents();
        this.setBackground(Color.white);
        
        
    }

    @Override
    public void paintComponent(Graphics g) {
        
        super.paintComponent(g);
        
        g.setColor(Color.black);
        
        if(Puntos != null){
            g.drawLine(0, 5000, (int)Puntos.get(Puntos.size()-1).getX(), 5000);
            g.drawLine(5, 0, 5, 5000);
            //g.drawLine(0, WIDTH, 0, WIDTH);
            for (int i = 0; i < Puntos.size(); i++) {
                g.drawOval((int)Puntos.get(i).getX(), (int)Puntos.get(i).getY(), 10, 10);
            }
            
            if(this.trio_mas_cercano != null){
                g.setColor(Color.red);
                Punto[] Puntos = this.trio_mas_cercano.getPuntos();
                g.drawLine((int)Puntos[0].getX(), (int)Puntos[0].getY(), (int)Puntos[1].getX(), (int)Puntos[1].getY());
                g.drawLine((int)Puntos[0].getX(), (int)Puntos[0].getY(), (int)Puntos[2].getX(), (int)Puntos[2].getY());
            }
        }
        //g.drawRect(100, 100, 1000, 50);

    }
    
    @Override
    public void update(Graphics g){
        paint(g);
    }
    
    public void cargarPuntos(ArrayList<Punto> Puntos){
        this.Puntos = Puntos;
        this.trio_mas_cercano = null;
        repaint();
    }
    
    public void setTrio(Trio T){
        
        this.trio_mas_cercano = T;
        repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
